# Generated by Django 4.1.7 on 2023-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixiv_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='translate_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
