# Generated by Django 4.1.7 on 2023-04-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixiv_model', '0003_image_path_alter_tag_translate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(default='D:\\bot\\awesomebot\\mylibrary', max_length=100),
        ),
    ]
