# Generated by Django 4.1.7 on 2023-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixiv_model', '0004_alter_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='unknown author', max_length=100),
        ),
    ]
