# Generated by Django 4.2.3 on 2023-11-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixiv_model', '0005_image_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixivToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
            ],
        ),
    ]
