# Generated by Django 4.2.3 on 2023-12-02 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pixiv_model', '0006_pixivtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixivtoken',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
