# Generated by Django 4.2.3 on 2023-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixiv_model', '0007_pixivtoken_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixivtoken',
            name='expires_in',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
